version: "3.1"
services:
    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
    nest_api:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - 3000:3000
        depends_on:
            - mongo
        volumes:
            - ./src:/usr/src/app/src
    mongo-express:
        image: mongo-express
        restart: always
        depends_on:
            - mongo
        ports:
            - 8080:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: root
            ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
            ME_CONFIG_BASICAUTH: false
